-- AlterTable
ALTER TABLE "companies" ALTER COLUMN "cin" SET DATA TYPE TEXT,
ALTER COLUMN "esic_registration" SET DATA TYPE TEXT,
ALTER COLUMN "gstin" SET DATA TYPE TEXT,
ALTER COLUMN "pf_registration" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "employees" ALTER COLUMN "bank_account" SET DATA TYPE TEXT,
ALTER COLUMN "pan" SET DATA TYPE TEXT,
ALTER COLUMN "pf_account" SET DATA TYPE TEXT,
ALTER COLUMN "uan" SET DATA TYPE TEXT;
