import { Router } from "express";
import { z } from "zod";
import { authenticate } from "../../middlewares/auth";
import { requirePermission, requireRole } from "../../middlewares/rbac";
import { validate } from "../../middlewares/validate";
import * as c from "./security.controller";

const router = Router();
const write = [requireRole("ADMIN"), requirePermission("security:write")];
router.use(authenticate, requireRole("ADMIN"));
router.get("/roles", requirePermission("security:read"), c.roles);
router.get("/permissions", requirePermission("security:read"), c.permissions);
router.post("/roles", ...write, validate({ body: z.object({ name: z.string().trim().min(2).max(50) }).strict() }), c.createRole);
router.delete("/roles/:id", ...write, c.deleteRole);
router.patch("/roles/:id/permissions", ...write, validate({ body: z.object({ permission: z.string().trim().min(3).max(80), granted: z.boolean() }).strict() }), c.setPermission);
router.patch("/roles/:id/mfa", ...write, validate({ body: z.object({ enabled: z.boolean(), exception: z.object({ reason: z.string().optional(), approvedBy: z.string().optional() }).optional() }).strict() }), c.setRoleMfa);
router.get("/users", requirePermission("security:read"), c.users);
router.post("/users", ...write, validate({ body: z.object({ name: z.string().trim().min(2), email: z.string().email(), roleId: z.string().uuid() }).strict() }), c.createUser);
router.patch("/users/:id/deactivate", ...write, c.deactivateUser);
router.patch("/users/:id/force-password-reset", ...write, c.forcePasswordReset);
router.delete("/users/:id/sessions", ...write, c.revokeSessions);
router.post("/break-glass", ...write, validate({ body: z.object({ justification: z.string().trim().min(10).max(2000) }).strict() }), c.breakGlass);
router.get("/sessions", requirePermission("security:read"), c.sessions);
router.get("/config", requirePermission("security:read"), c.config);
router.patch("/config/password-policy", ...write, c.passwordPolicy);
router.patch("/config/sso", ...write, c.sso);
router.patch("/config/session-policy", ...write, c.sessionPolicy);
router.patch("/config/ip-restrictions/:id", ...write, validate({ body: z.object({ allowedCidrs: z.array(z.string()), enabled: z.boolean() }).strict() }), c.ipRestriction);
router.get("/kms", requirePermission("security:read"), c.kms);
router.post("/kms/rotate", ...write, c.rotateKms);
router.get("/backups", requirePermission("security:read"), c.backups);
router.get("/restores", requirePermission("security:read"), c.restores);
router.post("/restores", ...write, validate({ body: z.object({ reason: z.string().trim().min(10).max(2000) }).strict() }), c.requestRestore);
router.post("/restores/:id/approve", ...write, validate({ body: z.object({ approverName: z.string().optional() }).strict() }), c.approveRestore);
router.post("/restores/:id/execute", ...write, c.executeRestore);
router.get("/audit", requirePermission("security:read"), c.audit);
router.get("/audit/verify", requirePermission("security:read"), c.verifyAudit);
export default router;
