apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hrms
type: Opaque

stringData:
  POSTGRES_USER: "YOUR_POSTGRES_USER"
  POSTGRES_PASSWORD: "YOUR_POSTGRES_PASSWORD"
  POSTGRES_DB: "YOUR_POSTGRES_DB"
  DATABASE_URL: "postgresql://YOUR_POSTGRES_USER:YOUR_POSTGRES_PASSWORD@db:5432/YOUR_POSTGRES_DB?schema=public"