apiVersion: v1
kind: Secret
metadata:
  name: hrms-common-secret
  namespace: hrms

type: Opaque

stringData:

  # Database
  DATABASE_URL: "postgresql://USERNAME:PASSWORD@db:5432/DATABASE?schema=public"

  # JWT
  JWT_ACCESS_SECRET: "CHANGE_ME_ACCESS_SECRET"
  JWT_REFRESH_SECRET: "CHANGE_ME_REFRESH_SECRET"

  # PII Encryption
  PII_ENCRYPTION_KEY: "CHANGE_ME_PII_ENCRYPTION_KEY"

  # MinIO
  MINIO_ACCESS_KEY: "CHANGE_ME_MINIO_ACCESS_KEY"
  MINIO_SECRET_KEY: "CHANGE_ME_MINIO_SECRET_KEY"

  # SMTP
  SMTP_USER: "your-email@example.com"
  SMTP_PASS: "CHANGE_ME_SMTP_PASSWORD"
  SMTP_FROM_EMAIL: "your-email@example.com"