import api from "./api";
const data = (response) => ({ data: response.data.data });
export const getRoles = () => api.get("/security/roles").then(data);
export const getPermissionCatalog = () => api.get("/security/permissions").then(data);
export const grantPermission = (roleId, permission) => api.patch(`/security/roles/${roleId}/permissions`, { permission, granted: true }).then((r) => ({ data: { role: r.data.data } }));
export const revokePermission = (roleId, permission) => api.patch(`/security/roles/${roleId}/permissions`, { permission, granted: false }).then((r) => ({ data: { role: r.data.data } }));
export const deleteRole = (roleId) => api.delete(`/security/roles/${roleId}`).then(data);
export const createCustomRole = (name) => api.post("/security/roles", { name }).then(data);
export const setRoleMfa = (roleId, enabled, exception) => api.patch(`/security/roles/${roleId}/mfa`, { enabled, exception }).then((r) => ({ data: { role: r.data.data } }));
export const getUsers = () => api.get("/security/users").then(data);
export const createUser = (user) => api.post("/security/users", { name: user.name, email: user.email, roleId: user.roleIds[0] }).then(data);
export const deactivateUser = (userId) => api.patch(`/security/users/${userId}/deactivate`).then((r) => ({ data: { user: r.data.data } }));
export const forcePasswordReset = (userId) => api.patch(`/security/users/${userId}/force-password-reset`).then((r) => ({ data: { user: r.data.data } }));
export const revokeAllSessions = (userId) => api.delete(`/security/users/${userId}/sessions`).then(data);
export const activateBreakGlass = (justification) => api.post("/security/break-glass", { justification }).then(data);
export const getSessions = () => api.get("/security/sessions").then(data);
export const getSecurityConfig = () => api.get("/security/config").then(data);
export const updatePasswordPolicy = (policy) => api.patch("/security/config/password-policy", policy).then(data);
export const updateSsoConfig = (config) => api.patch("/security/config/sso", config).then(data);
export const updateSessionPolicy = (policy) => api.patch("/security/config/session-policy", policy).then(data);
export const updateIpRestriction = (id, allowedCidrs, enabled) => api.patch(`/security/config/ip-restrictions/${id}`, { allowedCidrs, enabled }).then(data);
export const getKmsConfig = () => api.get("/security/kms").then(data);
export const rotateKmsKey = () => api.post("/security/kms/rotate").then(data);
export const getBackupJobs = () => api.get("/security/backups").then(data);
export const getRestoreRequests = () => api.get("/security/restores").then(data);
export const requestRestore = (reason) => api.post("/security/restores", { reason }).then(data);
export const approveRestore = (requestId, approverName) => api.post(`/security/restores/${requestId}/approve`, { approverName }).then((r) => ({ data: { request: r.data.data } }));
export const executeRestore = (requestId) => api.post(`/security/restores/${requestId}/execute`).then((r) => ({ data: { request: r.data.data } }));
export const getAuditLog = () => api.get("/security/audit").then(data);
export const verifyAuditChain = () => api.get("/security/audit/verify").then(data);
