import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Clock, Download, Lock, Play } from "lucide-react";
import MainLayout from "../../components/layout/MainLayout";
import PageHeader from "../../components/shared/PageHeader";
import Spinner from "../../components/shared/Spinner";
import EmptyState from "../../components/shared/EmptyState";
import { useAuth } from "../../context/AuthContext";
import { exportReportCsv, getFieldCatalog, getOrgScope, getReportTemplates, runCustomReport, runStandardReport } from "../../services/reportsService";

const card = { background: "var(--card)", border: "1px solid var(--border)", borderRadius: "var(--radius-lg)", boxShadow: "var(--shadow-sm)" };
const input = { height: 36, padding: "0 10px", border: "1px solid var(--border)", borderRadius: "var(--radius-sm)", background: "var(--card)", color: "var(--text)" };
const errorText = (error) => error?.response?.data?.error?.message || error?.response?.data?.message || error?.message || "Unable to run report";

function Button({ children, secondary, ...props }) {
  return <button {...props} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "9px 14px", border: secondary ? "1px solid var(--border)" : 0, borderRadius: "var(--radius-sm)", background: secondary ? "var(--card)" : "var(--primary)", color: secondary ? "var(--text)" : "#fff", fontWeight: 700, fontSize: 12.5, cursor: props.disabled ? "not-allowed" : "pointer", opacity: props.disabled ? .6 : 1 }}>{children}</button>;
}

function Filters({ scope, departments, setDepartments, location, setLocation }) {
  const toggle = (name) => setDepartments((current) => current.includes(name) ? current.filter((x) => x !== name) : [...current, name]);
  return <div style={{ ...card, padding: 16 }}><p style={{ fontSize: 11, fontWeight: 800, color: "var(--subtext)", textTransform: "uppercase", marginBottom: 9 }}>Report filters</p><div style={{ display: "grid", gap: 13 }}><div><p style={{ fontSize: 12, marginBottom: 6 }}>Department ({scope.name})</p><div style={{ display: "flex", flexWrap: "wrap", gap: 9 }}>{scope.departments.map((name) => <label key={name} style={{ fontSize: 12.5, display: "flex", gap: 5 }}><input type="checkbox" checked={departments.includes(name)} onChange={() => toggle(name)} />{name}</label>)}</div></div><label style={{ fontSize: 12 }}>Location<br /><select style={{ ...input, marginTop: 5, minWidth: 190 }} value={location} onChange={(e) => setLocation(e.target.value)}><option value="">All locations</option>{scope.locations.map((name) => <option key={name}>{name}</option>)}</select></label></div></div>;
}

function Result({ output, columns }) {
  return <div><p style={{ display: "flex", alignItems: "center", gap: 6, color: "var(--subtext)", fontSize: 12, marginBottom: 10 }}><Clock size={13} /> Data as of {new Date(output.dataAsOf).toLocaleString("en-IN")}</p><div style={{ ...card, overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr style={{ background: "var(--background)" }}><th style={th}>Group</th><th style={th}>Employees in group</th>{columns.map((x) => <th key={x.id} style={th}>{x.label}</th>)}</tr></thead><tbody>{output.rows.map((row) => <tr key={row.group} style={{ borderTop: "1px solid var(--border)" }}><td style={td}><strong>{row.group}</strong></td><td style={td}>{row.n}</td>{row.suppressed ? <td style={{ ...td, color: "var(--red)" }} colSpan={columns.length}><Lock size={12} /> {row.suppressionMessage}</td> : columns.map((column) => <td key={column.id} style={td}>{columns.length === 1 ? row.value : row.metrics[column.id]}</td>)}</tr>)}</tbody></table></div></div>;
}
const th = { padding: "11px 14px", textAlign: "left", fontSize: 11, color: "var(--subtext)", textTransform: "uppercase" };
const td = { padding: "12px 14px", fontSize: 12.5 };

function Standard({ templates, scope, canExport }) {
  const [templateId, setTemplateId] = useState(templates[0]?.id || ""); const [departments, setDepartments] = useState(scope.departments); const [location, setLocation] = useState(""); const [output, setOutput] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const template = templates.find((x) => x.id === templateId);
  const run = async () => { setLoading(true); setError(""); try { setOutput((await runStandardReport(templateId, { departments, location })).data); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } };
  const download = async () => { try { const result = (await exportReportCsv(templateId, { departments, location })).data; const blob = new Blob([result.csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = result.filename; link.click(); URL.revokeObjectURL(url); } catch (e) { setError(errorText(e)); } };
  return <div style={{ display: "grid", gridTemplateColumns: "minmax(210px, 260px) minmax(0, 1fr)", gap: 18, alignItems: "start" }}><div style={{ ...card, padding: 9 }}>{templates.map((item) => <button key={item.id} onClick={() => { setTemplateId(item.id); setOutput(null); }} style={{ display: "block", width: "100%", textAlign: "left", padding: "10px 11px", borderRadius: 7, border: templateId === item.id ? "1px solid var(--primary)" : "1px solid transparent", background: templateId === item.id ? "var(--primary-light)" : "transparent", color: templateId === item.id ? "var(--primary)" : "var(--text)", fontWeight: templateId === item.id ? 700 : 500, cursor: "pointer" }}>{item.name}</button>)}</div><div style={{ display: "grid", gap: 14 }}><Filters scope={scope} departments={departments} setDepartments={setDepartments} location={location} setLocation={setLocation} /><div style={{ display: "flex", gap: 8 }}><Button onClick={run} disabled={loading || !templateId}><Play size={14} />{loading ? "Running..." : "Run report"}</Button>{output && canExport && <Button secondary onClick={download}><Download size={14} />Export CSV</Button>}</div>{error && <p style={{ color: "var(--red)", fontSize: 12 }}><AlertTriangle size={13} /> {error}</p>}{loading && <Spinner />}{output ? <Result output={output} columns={[{ id: "value", label: template.metricLabel }]} /> : !loading && <EmptyState title="Run a standard report" subtitle="Aggregated results will appear here." />}</div></div>;
}

function Custom({ catalog, scope }) {
  const [dimensionId, setDimensionId] = useState(catalog.dimensions[0]?.id || "department"); const [metrics, setMetrics] = useState([catalog.metrics[0]?.id].filter(Boolean)); const [departments, setDepartments] = useState(scope.departments); const [location, setLocation] = useState(""); const [output, setOutput] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const selectedColumns = useMemo(() => metrics.map((id) => catalog.metrics.find((x) => x.id === id)).filter(Boolean), [catalog.metrics, metrics]);
  const toggleMetric = (id) => setMetrics((current) => current.includes(id) ? current.filter((x) => x !== id) : [...current, id]);
  const run = async () => { if (!metrics.length) { setError("Select at least one metric"); return; } setLoading(true); setError(""); try { setOutput((await runCustomReport({ dimensionId, metricIds: metrics, filters: { departments, location } })).data); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } };
  return <div style={{ display: "grid", gap: 14 }}><div style={{ ...card, padding: 16 }}><p style={{ fontSize: 11, fontWeight: 800, color: "var(--subtext)", textTransform: "uppercase" }}>Group by</p><div style={{ display: "flex", gap: 9, flexWrap: "wrap", margin: "7px 0 14px" }}>{catalog.dimensions.map((item) => <label key={item.id} style={{ fontSize: 12.5 }}><input type="radio" checked={dimensionId === item.id} onChange={() => setDimensionId(item.id)} /> {item.label} <small>{item.classification}</small></label>)}</div><p style={{ fontSize: 11, fontWeight: 800, color: "var(--subtext)", textTransform: "uppercase" }}>Metrics</p><div style={{ display: "flex", gap: 9, flexWrap: "wrap", marginTop: 7 }}>{catalog.metrics.map((item) => <label key={item.id} style={{ fontSize: 12.5 }}><input type="checkbox" checked={metrics.includes(item.id)} onChange={() => toggleMetric(item.id)} /> {item.label} <small>{item.classification}</small></label>)}</div><p style={{ fontSize: 11.5, color: "var(--subtext)", marginTop: 10 }}>Only approved aggregated fields are available. PII, bank details and free-text reviews are excluded.</p></div><Filters scope={scope} departments={departments} setDepartments={setDepartments} location={location} setLocation={setLocation} /><Button onClick={run} disabled={loading} style={{ width: "fit-content" }}><Play size={14} />{loading ? "Running..." : "Run custom report"}</Button>{error && <p style={{ color: "var(--red)" }}>{error}</p>}{output && <Result output={output} columns={selectedColumns} />}</div>;
}

export default function Reports() {
  const { role, permissions } = useAuth(); const [tab, setTab] = useState("standard"); const [templates, setTemplates] = useState([]); const [scope, setScope] = useState(null); const [catalog, setCatalog] = useState(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const [t, s, c] = await Promise.all([getReportTemplates(), getOrgScope(), getFieldCatalog()]); setTemplates(t.data); setScope(s.data); setCatalog(c.data); } catch (e) { setError(errorText(e)); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);
  if (!["ADMIN", "HR", "MANAGER"].includes(role)) return <MainLayout><EmptyState icon={Lock} title="Reports access is restricted" /></MainLayout>;
  if (!scope || !catalog) return <MainLayout><Spinner /></MainLayout>;
  return <MainLayout><div style={{ maxWidth: 1480, margin: "0 auto" }}><PageHeader title="Reports & Analytics" subtitle="Role-scoped workforce insights over approved aggregated fields" />{error && <p style={{ color: "var(--red)", marginBottom: 12 }}>{error}</p>}<div style={{ display: "flex", gap: 3, borderBottom: "1px solid var(--border)", marginBottom: 17 }}>{[["standard", "Standard Reports"], ["custom", "Custom Builder"]].map(([id, label]) => <button key={id} onClick={() => setTab(id)} style={{ padding: "10px 17px", background: "none", border: 0, borderBottom: tab === id ? "2px solid var(--primary)" : "2px solid transparent", color: tab === id ? "var(--primary)" : "var(--subtext)", fontWeight: 700, cursor: "pointer" }}>{label}</button>)}</div>{tab === "standard" ? <Standard templates={templates} scope={scope} canExport={permissions.includes("reports:export")} /> : <Custom catalog={catalog} scope={scope} />}</div></MainLayout>;
}
