apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: hrms
spec:
  selector:
    app: expense-service
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  type: ClusterIP
